# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ActionCall:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectAction", llm_response=llm_response, mode="request")
        return typing.cast(types.ActionCall, __result__)

    def ExtractLessons(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.LessonOps:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractLessons", llm_response=llm_response, mode="request")
        return typing.cast(types.LessonOps, __result__)

    def ExtractStatement(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.StatementPage:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStatement", llm_response=llm_response, mode="request")
        return typing.cast(types.StatementPage, __result__)

    def MapColumns(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ColumnMap:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapColumns", llm_response=llm_response, mode="request")
        return typing.cast(types.ColumnMap, __result__)

    def MapCrypto(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CryptoMap:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapCrypto", llm_response=llm_response, mode="request")
        return typing.cast(types.CryptoMap, __result__)

    def PickSkills(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SkillPick:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PickSkills", llm_response=llm_response, mode="request")
        return typing.cast(types.SkillPick, __result__)

    def PlanQueries(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.QueryPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanQueries", llm_response=llm_response, mode="request")
        return typing.cast(types.QueryPlan, __result__)

    def PlanRoutines(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoutinePlans:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanRoutines", llm_response=llm_response, mode="request")
        return typing.cast(types.RoutinePlans, __result__)

    def ProposePeers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PeerPicks:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ProposePeers", llm_response=llm_response, mode="request")
        return typing.cast(types.PeerPicks, __result__)

    def ResolveSymbols(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Dict[str, typing.Optional[str]]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ResolveSymbols", llm_response=llm_response, mode="request")
        return typing.cast(typing.Dict[str, typing.Optional[str]], __result__)

    def WriteAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnalysisReply:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="WriteAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(types.AnalysisReply, __result__)

    def WriteDailyCard(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CardReply:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="WriteDailyCard", llm_response=llm_response, mode="request")
        return typing.cast(types.CardReply, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ActionCall:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetectAction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ActionCall, __result__)

    def ExtractLessons(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.LessonOps:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractLessons", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.LessonOps, __result__)

    def ExtractStatement(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.StatementPage:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractStatement", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.StatementPage, __result__)

    def MapColumns(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ColumnMap:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapColumns", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ColumnMap, __result__)

    def MapCrypto(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CryptoMap:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapCrypto", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CryptoMap, __result__)

    def PickSkills(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SkillPick:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PickSkills", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SkillPick, __result__)

    def PlanQueries(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.QueryPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanQueries", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.QueryPlan, __result__)

    def PlanRoutines(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoutinePlans:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanRoutines", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoutinePlans, __result__)

    def ProposePeers(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PeerPicks:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ProposePeers", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PeerPicks, __result__)

    def ResolveSymbols(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Dict[str, typing.Optional[str]]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ResolveSymbols", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Dict[str, typing.Optional[str]], __result__)

    def WriteAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnalysisReply:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="WriteAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnalysisReply, __result__)

    def WriteDailyCard(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CardReply:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="WriteDailyCard", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CardReply, __result__)

    