# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (16)
# #########################################################################

class ActionCall(BaseModel):
    action: typing.Optional[str] = Field(default=None, description='the action name, or null when the message asks for no change')
    ticker: typing.Optional[str] = Field(default=None, description='the symbol the action targets')
    alerts: typing.Optional[typing.List["AlertRule"]] = None
    tags: typing.Optional[typing.List[str]] = None
    name: typing.Optional[str] = None
    shares: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    cost: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')

class AlertRule(BaseModel):
    type: typing.Optional[str] = Field(default=None, description='above or below')
    price: typing.Optional[typing.Union[float, str]] = None

class AnalysisPoint(BaseModel):
    title: typing.Optional[str] = None
    text: typing.Optional[str] = None

class AnalysisReply(BaseModel):
    verdict: typing.Optional[str] = None
    points: typing.Optional[typing.List["AnalysisPoint"]] = None

class CardLine(BaseModel):
    key: typing.Optional[str] = Field(default=None, description='the key of the action the line is about, copied exactly')
    line: typing.Optional[str] = None

class CardReply(BaseModel):
    headline: typing.Optional[str] = None
    items: typing.Optional[typing.List["CardLine"]] = None
    focus: typing.Optional[typing.List[str]] = None
    routines: typing.Optional[typing.List["RoutineAnswer"]] = None

class ColumnMap(BaseModel):
    header_row: typing.Optional[int] = Field(default=None, description='index of the row holding the column headers')
    columns: typing.Optional["Columns"] = Field(default=None, description='0-based column index per field, or null for the whole object when the file cannot be mapped')
    date_format: typing.Optional[str] = Field(default=None, description='strftime format of the date cells, e.g. %d/%m/%Y')
    decimal: typing.Optional[str] = Field(default=None, description='the decimal separator, \'.\' or \',\'')
    thousands: typing.Optional[str] = Field(default=None, description='the thousands separator, or an empty string')
    asset_class: typing.Optional[types.AssetClass] = None
    action_map: typing.Optional[typing.Dict[str, str]] = Field(default=None, description='the exact text in the action column -> buy, sell, dividend, fee or split')

class Columns(BaseModel):
    date: typing.Optional[int] = None
    ticker: typing.Optional[int] = None
    action: typing.Optional[int] = None
    quantity: typing.Optional[int] = None
    price: typing.Optional[int] = None
    amount: typing.Optional[int] = None
    currency: typing.Optional[int] = None
    fee: typing.Optional[int] = None
    note: typing.Optional[int] = None

class LessonOp(BaseModel):
    op: typing.Optional[str] = Field(default=None, description='add, update or delete')
    id: typing.Optional[str] = Field(default=None, description='the saved item\'s id, for update and delete')
    kind: typing.Optional[str] = Field(default=None, description='preference, goal, decision, constraint, context or routine')
    text: typing.Optional[str] = None

class LessonOps(BaseModel):
    ops: typing.Optional[typing.List["LessonOp"]] = None

class PeerPicks(BaseModel):
    symbols: typing.Optional[typing.List[str]] = Field(default=None, description='Yahoo Finance symbols, exchange suffix included')

class QueryPlan(BaseModel):
    queries: typing.Optional[typing.List[str]] = Field(default=None, description='web search queries; empty when none is needed')

class RoutineAnswer(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='the `id` of the routine in the data, copied exactly')
    answer: typing.Optional[str] = None

class SkillPick(BaseModel):
    skills: typing.Optional[typing.List[str]] = Field(default=None, description='skill ids from the catalog')

class StatementPage(BaseModel):
    kind: typing.Optional[types.DocumentKind] = None
    transactions: typing.Optional[typing.List["StatementRow"]] = None

class StatementRow(BaseModel):
    date: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    ticker: typing.Optional[str] = Field(default=None, description='symbol or ISIN')
    action: typing.Optional[str] = Field(default=None, description='buy, sell, dividend, fee or split')
    quantity: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    price: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    currency: typing.Optional[str] = Field(default=None, description='3-letter code')
    fee: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    note: typing.Optional[str] = Field(default=None, description='short label, optional')

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (16)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
ActionCall.model_rebuild()
AlertRule.model_rebuild()
AnalysisPoint.model_rebuild()
AnalysisReply.model_rebuild()
CardLine.model_rebuild()
CardReply.model_rebuild()
ColumnMap.model_rebuild()
Columns.model_rebuild()
LessonOp.model_rebuild()
LessonOps.model_rebuild()
PeerPicks.model_rebuild()
QueryPlan.model_rebuild()
RoutineAnswer.model_rebuild()
SkillPick.model_rebuild()
StatementPage.model_rebuild()
StatementRow.model_rebuild()
