# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def DetectAction(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ActionCall:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DetectAction(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DetectAction", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.ActionCall, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractLessons(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.LessonOps:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractLessons(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractLessons", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.LessonOps, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractStatement(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.StatementPage:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractStatement(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractStatement", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.StatementPage, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def MapColumns(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ColumnMap:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.MapColumns(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="MapColumns", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.ColumnMap, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def PickSkills(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SkillPick:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.PickSkills(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="PickSkills", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.SkillPick, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def PlanQueries(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.QueryPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.PlanQueries(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="PlanQueries", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.QueryPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ProposePeers(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PeerPicks:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ProposePeers(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ProposePeers", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.PeerPicks, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ResolveSymbols(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Dict[str, typing.Optional[str]]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ResolveSymbols(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ResolveSymbols", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(typing.Dict[str, typing.Optional[str]], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def WriteAnalysis(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnalysisReply:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.WriteAnalysis(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="WriteAnalysis", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.AnalysisReply, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def WriteDailyCard(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CardReply:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.WriteDailyCard(instructions=instructions,input=input,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="WriteDailyCard", args={
                "instructions": instructions,"input": input,
            })
            return typing.cast(types.CardReply, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectAction(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ActionCall, types.ActionCall]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DetectAction", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.ActionCall, types.ActionCall](
          __result__,
          lambda x: typing.cast(stream_types.ActionCall, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ActionCall, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractLessons(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.LessonOps, types.LessonOps]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractLessons", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.LessonOps, types.LessonOps](
          __result__,
          lambda x: typing.cast(stream_types.LessonOps, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.LessonOps, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractStatement(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.StatementPage, types.StatementPage]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractStatement", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.StatementPage, types.StatementPage](
          __result__,
          lambda x: typing.cast(stream_types.StatementPage, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.StatementPage, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def MapColumns(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ColumnMap, types.ColumnMap]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="MapColumns", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.ColumnMap, types.ColumnMap](
          __result__,
          lambda x: typing.cast(stream_types.ColumnMap, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ColumnMap, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PickSkills(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SkillPick, types.SkillPick]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="PickSkills", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.SkillPick, types.SkillPick](
          __result__,
          lambda x: typing.cast(stream_types.SkillPick, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SkillPick, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PlanQueries(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.QueryPlan, types.QueryPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="PlanQueries", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.QueryPlan, types.QueryPlan](
          __result__,
          lambda x: typing.cast(stream_types.QueryPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.QueryPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ProposePeers(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PeerPicks, types.PeerPicks]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ProposePeers", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.PeerPicks, types.PeerPicks](
          __result__,
          lambda x: typing.cast(stream_types.PeerPicks, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PeerPicks, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ResolveSymbols(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Dict[str, typing.Optional[str]], typing.Dict[str, typing.Optional[str]]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ResolveSymbols", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[typing.Dict[str, typing.Optional[str]], typing.Dict[str, typing.Optional[str]]](
          __result__,
          lambda x: typing.cast(typing.Dict[str, typing.Optional[str]], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Dict[str, typing.Optional[str]], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def WriteAnalysis(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AnalysisReply, types.AnalysisReply]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="WriteAnalysis", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.AnalysisReply, types.AnalysisReply](
          __result__,
          lambda x: typing.cast(stream_types.AnalysisReply, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnalysisReply, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def WriteDailyCard(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CardReply, types.CardReply]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="WriteDailyCard", args={
            "instructions": instructions,"input": input,
        })
        return baml_py.BamlSyncStream[stream_types.CardReply, types.CardReply](
          __result__,
          lambda x: typing.cast(stream_types.CardReply, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CardReply, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectAction(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetectAction", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def ExtractLessons(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractLessons", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def ExtractStatement(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStatement", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def MapColumns(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MapColumns", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def PickSkills(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PickSkills", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def PlanQueries(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanQueries", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def ProposePeers(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ProposePeers", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def ResolveSymbols(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ResolveSymbols", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def WriteAnalysis(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="WriteAnalysis", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    def WriteDailyCard(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="WriteDailyCard", args={
            "instructions": instructions,"input": input,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetectAction(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DetectAction", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def ExtractLessons(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractLessons", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def ExtractStatement(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractStatement", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def MapColumns(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MapColumns", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def PickSkills(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PickSkills", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def PlanQueries(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanQueries", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def ProposePeers(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ProposePeers", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def ResolveSymbols(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ResolveSymbols", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def WriteAnalysis(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="WriteAnalysis", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    def WriteDailyCard(self, instructions: str,input: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="WriteDailyCard", args={
            "instructions": instructions,"input": input,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))