# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class AssetClass(str, Enum):
    Crypto = "Crypto"
    Securities = "Securities"

class DocumentKind(str, Enum):
    Trades = "Trades"
    Positions = "Positions"
    Neither = "Neither"

# #########################################################################
# Generated classes (16)
# #########################################################################

class ActionCall(BaseModel):
    action: typing.Optional[str] = Field(default=None, description='the action name, or null when the message asks for no change')
    ticker: typing.Optional[str] = Field(default=None, description='the symbol the action targets')
    alerts: typing.Optional[typing.List["AlertRule"]] = None
    tags: typing.Optional[typing.List[str]] = None
    name: typing.Optional[str] = None
    shares: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    cost: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    broker: typing.Optional[str] = Field(default=None, description='one lowercase word: degiro, ibkr, revolut')
    to_broker: typing.Optional[str] = Field(default=None, description='the broker the shares moved to')
    date: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    since: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    until: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    trade: typing.Optional[str] = Field(default=None, description='buy, sell, dividend, fee, split, transfer_in or transfer_out')
    quantity: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    price: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    fee: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    currency: typing.Optional[str] = Field(default=None, description='ISO code, like EUR')
    to: typing.Optional[str] = Field(default=None, description='the symbol to book the rows under instead')
    ids: typing.Optional[typing.List[typing.Union[int, str]]] = Field(default=None, description='row numbers the user quoted')
    new_date: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    new_quantity: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    new_price: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    new_fee: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')

class AlertRule(BaseModel):
    type: typing.Optional[str] = Field(default=None, description='above or below')
    price: typing.Optional[typing.Union[float, str]] = None

class AnalysisPoint(BaseModel):
    title: typing.Optional[str] = None
    text: typing.Optional[str] = None

class AnalysisReply(BaseModel):
    verdict: typing.Optional[str] = None
    points: typing.Optional[typing.List["AnalysisPoint"]] = None

class CardLine(BaseModel):
    key: typing.Optional[str] = Field(default=None, description='the key of the action the line is about, copied exactly')
    line: typing.Optional[str] = None

class CardReply(BaseModel):
    headline: typing.Optional[str] = None
    items: typing.Optional[typing.List["CardLine"]] = None
    focus: typing.Optional[typing.List[str]] = None
    routines: typing.Optional[typing.List["RoutineAnswer"]] = None

class ColumnMap(BaseModel):
    header_row: typing.Optional[int] = Field(default=None, description='index of the row holding the column headers')
    columns: typing.Optional["Columns"] = Field(default=None, description='0-based column index per field, or null for the whole object when the file cannot be mapped')
    date_format: typing.Optional[str] = Field(default=None, description='strftime format of the date cells, e.g. %d/%m/%Y')
    decimal: typing.Optional[str] = Field(default=None, description='the decimal separator, \'.\' or \',\'')
    thousands: typing.Optional[str] = Field(default=None, description='the thousands separator, or an empty string')
    asset_class: typing.Optional[AssetClass] = None
    action_map: typing.Optional[typing.Dict[str, str]] = Field(default=None, description='the exact text in the action column -> buy, sell, dividend, fee or split')

class Columns(BaseModel):
    date: typing.Optional[int] = None
    ticker: typing.Optional[int] = None
    action: typing.Optional[int] = None
    quantity: typing.Optional[int] = None
    price: typing.Optional[int] = None
    amount: typing.Optional[int] = None
    currency: typing.Optional[int] = None
    fee: typing.Optional[int] = None
    note: typing.Optional[int] = None

class LessonOp(BaseModel):
    op: typing.Optional[str] = Field(default=None, description='add, update or delete')
    id: typing.Optional[str] = Field(default=None, description='the saved item\'s id, for update and delete')
    kind: typing.Optional[str] = Field(default=None, description='preference, goal, decision, constraint, context or routine')
    text: typing.Optional[str] = None

class LessonOps(BaseModel):
    ops: typing.Optional[typing.List["LessonOp"]] = None

class PeerPicks(BaseModel):
    symbols: typing.Optional[typing.List[str]] = Field(default=None, description='Yahoo Finance symbols, exchange suffix included')

class QueryPlan(BaseModel):
    queries: typing.Optional[typing.List[str]] = Field(default=None, description='web search queries; empty when none is needed')

class RoutineAnswer(BaseModel):
    id: typing.Optional[str] = Field(default=None, description='the `id` of the routine in the data, copied exactly')
    answer: typing.Optional[str] = None

class SkillPick(BaseModel):
    skills: typing.Optional[typing.List[str]] = Field(default=None, description='skill ids from the catalog')

class StatementPage(BaseModel):
    kind: typing.Optional[DocumentKind] = None
    transactions: typing.Optional[typing.List["StatementRow"]] = None

class StatementRow(BaseModel):
    date: typing.Optional[str] = Field(default=None, description='YYYY-MM-DD')
    ticker: typing.Optional[str] = Field(default=None, description='symbol or ISIN')
    action: typing.Optional[str] = Field(default=None, description='buy, sell, dividend, fee or split')
    quantity: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    price: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    currency: typing.Optional[str] = Field(default=None, description='3-letter code')
    fee: typing.Optional[typing.Union[float, str]] = Field(default=None, description='a plain number')
    note: typing.Optional[str] = Field(default=None, description='short label, optional')

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (16)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
ActionCall.model_rebuild()
AlertRule.model_rebuild()
AnalysisPoint.model_rebuild()
AnalysisReply.model_rebuild()
CardLine.model_rebuild()
CardReply.model_rebuild()
ColumnMap.model_rebuild()
Columns.model_rebuild()
LessonOp.model_rebuild()
LessonOps.model_rebuild()
PeerPicks.model_rebuild()
QueryPlan.model_rebuild()
RoutineAnswer.model_rebuild()
SkillPick.model_rebuild()
StatementPage.model_rebuild()
StatementRow.model_rebuild()
