# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ActionCall": types.ActionCall,
    "stream_types.ActionCall": stream_types.ActionCall,

    "types.AlertRule": types.AlertRule,
    "stream_types.AlertRule": stream_types.AlertRule,

    "types.AnalysisPoint": types.AnalysisPoint,
    "stream_types.AnalysisPoint": stream_types.AnalysisPoint,

    "types.AnalysisReply": types.AnalysisReply,
    "stream_types.AnalysisReply": stream_types.AnalysisReply,

    "types.CardLine": types.CardLine,
    "stream_types.CardLine": stream_types.CardLine,

    "types.CardReply": types.CardReply,
    "stream_types.CardReply": stream_types.CardReply,

    "types.ColumnMap": types.ColumnMap,
    "stream_types.ColumnMap": stream_types.ColumnMap,

    "types.Columns": types.Columns,
    "stream_types.Columns": stream_types.Columns,

    "types.LessonOp": types.LessonOp,
    "stream_types.LessonOp": stream_types.LessonOp,

    "types.LessonOps": types.LessonOps,
    "stream_types.LessonOps": stream_types.LessonOps,

    "types.PeerPicks": types.PeerPicks,
    "stream_types.PeerPicks": stream_types.PeerPicks,

    "types.QueryPlan": types.QueryPlan,
    "stream_types.QueryPlan": stream_types.QueryPlan,

    "types.RoutineAnswer": types.RoutineAnswer,
    "stream_types.RoutineAnswer": stream_types.RoutineAnswer,

    "types.SkillPick": types.SkillPick,
    "stream_types.SkillPick": stream_types.SkillPick,

    "types.StatementPage": types.StatementPage,
    "stream_types.StatementPage": stream_types.StatementPage,

    "types.StatementRow": types.StatementRow,
    "stream_types.StatementRow": stream_types.StatementRow,


    "types.AssetClass": types.AssetClass,

    "types.DocumentKind": types.DocumentKind,

}